<?php
/** -------------------------------------------------------------------------
 * This program is Open Source; you can redistribute it
 * and/or modify it under the terms of the GNU General Public License
 * This program is coded in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY
 * @package  CMS
 * @author     Kenwoo - iweb@kenwoo.ca
 * @license    http://creativecommons.org/licenses/by/4.0/ Creative Commons
 *
 * [v01-09/01/2015]:: Set flag, not allow to direct access
 *  ------------------------------------------------------------------------- */
defined( "_VALID_MOS" ) or die( "Your system is not working properly." );
?>
<div class="foot-right">
<a href="https://www.facebook.com/groups/tconnectchurch/" title="Facebook" target="_blank" class="facebook_icon"></a> <span class="logo_icon"></span>
<a href="https://www.youtube.com/channel/UCpZQ8_EhcKAiheE-gfaADrA" title="YouTube" target="_blank" class="youtube_icon"></a><br class="clearfix">
</div>
Copyright &copy; 2015 - Connect Church. All Rights Reserved.<br/>
교회:<a href="https://www.google.ca/maps/place/45+Davenport+Rd,+Toronto,+ON+M5R+1H2/@43.6727332,-79.3898326,17z/data=!3m1!4b1!4m2!3m1!1s0x882b34af3bfc37ab:0x5a9e19ec690eb61b" title="View Google Map" target="_blank">45 Davenport Road Toronto, ON <span class="disapearclass">M5R 1H2</span></a><br/>
목사관:<a href="https://www.google.ca/maps/place/269+Finch+Ave+W,+North+York,+ON+M2R+1M8/@43.7742657,-79.4393503,17z/data=!3m1!4b1!4m2!3m1!1s0x882b2d971fbf08db:0x1598808d697a5636" title="View Google Map" target="_blank">269 Finch Ave. West. North York ON M2R1M8</a> / 416-999-7878 & 647.800.0481/ tconnectchurch@gmail.com
